name: Check
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check format
        run: pnpm format:check
      - name: Install Playwright
        run: pnpm playwright install --with-deps
      - name: Build
        run: pnpm build
      - name: Run unit test
        run: pnpm test:unit
      - name: Run e2e test
        run: pnpm test:e2e:skipbuild --project=chromium
